### ISSUE TITLE
Does it work with template engines?

### ISSUE THREAD

**Issue by arturkin** [unbroken-dome/indexhtml-webpack-plugin#7]
It would be a good addition to this plugin to work with template engines like `jade`.
I tried `jade-html-loader` but no luck.

**Comment by squirmy** [comment]
Thought I'd have a look at this - good news it's possible. :)
Instead of using jade-html-loader, use template-html-loader (you also need jade installed).

This is the webpack config that worked for me:

``` javascript
var IndexHtmlPlugin = require('indexhtml-webpack-plugin');

module.exports = {
  entry: {
    "index.html": './src/index.jade',
    main: "./src/main.js"
  },
  output: {
    path: "./build",
    filename: "[name]-[chunkhash].js"
  },
  module: {
    loaders: [
      {
        test: /index\.jade$/,
        loader: 'template-html-loader'
      }
    ]
  },
  plugins: [
    new IndexHtmlPlugin('index.html', 'index.html')
  ]
}
```

**Comment by arturkin** [comment]
Thanks, it works but without HMR :(

**Comment by exdeniz** [comment]
Yes, works. But i want HMR. Please fixed.
